# Generated by Django 4.2 on 2023-04-28 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_customuser_age_alter_customuser_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='current_level',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
